services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${CTFD_DB_USER}
      MYSQL_PASSWORD: ${CTFD_DB_PASSWORD}
      MYSQL_DATABASE: ${CTFD_DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ctfd_net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - ctfd_net





  web-gallery:
    build: ./challenges/web/the_secret_archive
    ports:
      - "8002:5000"
    networks:
      - ctfd_net

  web-ping:
    build: ./challenges/web/ping_o_matic
    ports:
      - "8001:5000"
    networks:
      - ctfd_net

  web-cookies:
    build: ./challenges/web/VIP_Access_Session_Inspector
    ports:
      - "8003:5000"
    networks:
      - ctfd_net

  web-sqli:
    build: ./challenges/web/scout_database
    ports:
      - "8005:8005"
    networks:
      - ctfd_net


  web-pwn-var:
    build: ./challenges/pwn/var_review
    ports:
      - "8006:8006"
    networks:
      - ctfd_net
    restart: always

  web-var-check:
    build: ./challenges/web/var_check_bro
    ports:
      - "8007:5000"
    networks:
      - ctfd_net
    restart: always

  web-stadium-ci:
    build: ./challenges/web/stadium_ci
    ports:
      - "8008:5000"
    networks:
      - ctfd_net
    restart: always

  web-stadium-defi:
    build: ./challenges/web/stadium_defi
    ports:
      - "8009:5000"
      - "8010:8545"
    networks:
      - ctfd_net
    restart: always

  pwn-var-replay:
    build: ./challenges/pwn/var_replay_buffer
    ports:
      - "8011:8011"
    networks:
      - ctfd_net
    restart: always

  ot-scada:
    build: ./challenges/ot-scada/ait_baha_nuclear
    ports:
      - "8012:8012"
      - "5020:5020"
    networks:
      - ctfd_net
    restart: always

  coach-gpt:
    build: ./challenges/llm-mcp/coach_gpt_jailbreak
    ports:
      - "8013:8013"
    networks:
      - ctfd_net
    restart: always

  referee-briefing:
    build: ./challenges/llm-mcp/referee_briefing
    env_file:
      - ./challenges/llm-mcp/referee_briefing/.env
    ports:
      - "8014:8008"
    networks:
      - ctfd_net
    restart: always

  ot-scada-medport:
    build: ./challenges/ot-scada/agadir_medport
    ports:
      - "1884:1883"
    networks:
      - ctfd_net
    restart: always









  ctfd:
    image: ctfd/ctfd:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${CTFD_DB_USER}:${CTFD_DB_PASSWORD}@db:3306/${CTFD_DB_NAME}
      - REDIS_URL=redis://${CTFD_REDIS_HOST}:6379
      - UPLOAD_FOLDER=/var/uploads
      - SECRET_KEY=${CTFD_SECRET_KEY}
    volumes:
      - ctfd_data:/var/uploads
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - ctfd_net

volumes:
  db_data:
  ctfd_data:

networks:
  ctfd_net:
    driver: bridge
