[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
user=batistuta

[program:mariadb]
command=/usr/sbin/mariadbd --user=batistuta --datadir=/var/lib/mysql --socket=/var/run/mysqld/mysqld.sock --bind-address=127.0.0.1 --port=3306 --secure-file-priv= --skip-log-bin
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mariadb.log
stderr_logfile=/var/log/supervisor/mariadb.err

[program:web]
command=/usr/local/bin/python3 /opt/app/app.py
directory=/opt/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/web.log
stderr_logfile=/var/log/supervisor/web.err
environment=HMAC_SECRET="%(ENV_HMAC_SECRET)s",FLAG1_ENC_B64="%(ENV_FLAG1_ENC_B64)s",FLAG2_ENC_B64="%(ENV_FLAG2_ENC_B64)s"
