# Template — replace ping-o-matic, Web, 8080, NODE8080, IMAGE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-o-matic
  namespace: ctfd
  labels:
    app: ping-o-matic
    category: Web
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ping-o-matic
  template:
    metadata:
      labels:
        app: ping-o-matic
        category: Web
    spec:
      containers:
      - name: ping-o-matic
        image: registry.digitalocean.com/infodays-registry/ping-o-matic:latest
        ports:
        - containerPort: 8080
        env:
        - name: FLAG
          valueFrom:
            secretKeyRef:
              name: flags-TEAM_ID
              key: ping-o-matic
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ping-o-matic
  namespace: ctfd
spec:
  type: NodePort
  selector:
    app: ping-o-matic
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: NODE8080
