# Template — replace var-replay-buffer, Pwn, 1337, NODE1337, IMAGE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: var-replay-buffer
  namespace: ctfd
  labels:
    app: var-replay-buffer
    category: Pwn
spec:
  replicas: 0
  selector:
    matchLabels:
      app: var-replay-buffer
  template:
    metadata:
      labels:
        app: var-replay-buffer
        category: Pwn
    spec:
      containers:
      - name: var-replay-buffer
        image: registry.digitalocean.com/infodays-registry/var-replay-buffer:latest
        ports:
        - containerPort: 1337
        env:
        - name: FLAG
          valueFrom:
            secretKeyRef:
              name: flags-TEAM_ID
              key: var-replay-buffer
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: var-replay-buffer
  namespace: ctfd
spec:
  type: NodePort
  selector:
    app: var-replay-buffer
  ports:
  - port: 1337
    targetPort: 1337
    nodePort: NODE1337
